# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CurrencyConverter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for CurrencyConverter
  pod 'iCarousel'

  target 'CurrencyConverterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CurrencyConverterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
